# TCL File Generated by Component Editor 18.1
# Wed Apr 20 23:12:15 COT 2022
# DO NOT MODIFY


# 
# pid_controller "pid_controller" v1.0
#  2022.04.20.23:12:15
# a simple pid controller
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pid_controller
# 
set_module_property DESCRIPTION "a simple pid controller"
set_module_property NAME pid_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP custom
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pid_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pid_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pid_controller.vhd VHDL PATH ip/pid_controler/pid_controller.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter iDataWidith INTEGER 32
set_parameter_property iDataWidith DEFAULT_VALUE 32
set_parameter_property iDataWidith DISPLAY_NAME iDataWidith
set_parameter_property iDataWidith TYPE INTEGER
set_parameter_property iDataWidith ENABLED false
set_parameter_property iDataWidith UNITS None
set_parameter_property iDataWidith ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iDataWidith HDL_PARAMETER true
add_parameter iKP INTEGER 3
set_parameter_property iKP DEFAULT_VALUE 3
set_parameter_property iKP DISPLAY_NAME iKP
set_parameter_property iKP TYPE INTEGER
set_parameter_property iKP ENABLED false
set_parameter_property iKP UNITS None
set_parameter_property iKP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iKP HDL_PARAMETER true
add_parameter iKI INTEGER 2
set_parameter_property iKI DEFAULT_VALUE 2
set_parameter_property iKI DISPLAY_NAME iKI
set_parameter_property iKI TYPE INTEGER
set_parameter_property iKI ENABLED false
set_parameter_property iKI UNITS None
set_parameter_property iKI ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iKI HDL_PARAMETER true
add_parameter iKD INTEGER 2
set_parameter_property iKD DEFAULT_VALUE 2
set_parameter_property iKD DISPLAY_NAME iKD
set_parameter_property iKD TYPE INTEGER
set_parameter_property iKD ENABLED false
set_parameter_property iKD UNITS None
set_parameter_property iKD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iKD HDL_PARAMETER true
add_parameter iKM INTEGER 1
set_parameter_property iKM DEFAULT_VALUE 1
set_parameter_property iKM DISPLAY_NAME iKM
set_parameter_property iKM TYPE INTEGER
set_parameter_property iKM ENABLED false
set_parameter_property iKM UNITS None
set_parameter_property iKM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iKM HDL_PARAMETER true
add_parameter iDelayD INTEGER 10
set_parameter_property iDelayD DEFAULT_VALUE 10
set_parameter_property iDelayD DISPLAY_NAME iDelayD
set_parameter_property iDelayD TYPE INTEGER
set_parameter_property iDelayD ENABLED false
set_parameter_property iDelayD UNITS None
set_parameter_property iDelayD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iDelayD HDL_PARAMETER true
add_parameter iWork INTEGER 1
set_parameter_property iWork DEFAULT_VALUE 1
set_parameter_property iWork DISPLAY_NAME iWork
set_parameter_property iWork TYPE INTEGER
set_parameter_property iWork ENABLED false
set_parameter_property iWork UNITS None
set_parameter_property iWork ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iWork HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink CLK_I clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RESET_I reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end CORRECT_O writedata Output idatawidith


# 
# connection point PATERN_I
# 
add_interface PATERN_I avalon end
set_interface_property PATERN_I addressUnits WORDS
set_interface_property PATERN_I associatedClock clock_sink
set_interface_property PATERN_I associatedReset reset_sink
set_interface_property PATERN_I bitsPerSymbol 8
set_interface_property PATERN_I burstOnBurstBoundariesOnly false
set_interface_property PATERN_I burstcountUnits WORDS
set_interface_property PATERN_I explicitAddressSpan 0
set_interface_property PATERN_I holdTime 0
set_interface_property PATERN_I linewrapBursts false
set_interface_property PATERN_I maximumPendingReadTransactions 0
set_interface_property PATERN_I maximumPendingWriteTransactions 0
set_interface_property PATERN_I readLatency 0
set_interface_property PATERN_I readWaitTime 1
set_interface_property PATERN_I setupTime 0
set_interface_property PATERN_I timingUnits Cycles
set_interface_property PATERN_I writeWaitTime 0
set_interface_property PATERN_I ENABLED true
set_interface_property PATERN_I EXPORT_OF ""
set_interface_property PATERN_I PORT_NAME_MAP ""
set_interface_property PATERN_I CMSIS_SVD_VARIABLES ""
set_interface_property PATERN_I SVD_ADDRESS_GROUP ""

add_interface_port PATERN_I PATERN_I writedata Input idatawidith
add_interface_port PATERN_I avalon_slave_write write Input 1
set_interface_assignment PATERN_I embeddedsw.configuration.isFlash 0
set_interface_assignment PATERN_I embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment PATERN_I embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment PATERN_I embeddedsw.configuration.isPrintableDevice 0


# 
# connection point PATERN_ESTIMATION_I
# 
add_interface PATERN_ESTIMATION_I avalon end
set_interface_property PATERN_ESTIMATION_I addressUnits WORDS
set_interface_property PATERN_ESTIMATION_I associatedClock clock_sink
set_interface_property PATERN_ESTIMATION_I associatedReset reset_sink
set_interface_property PATERN_ESTIMATION_I bitsPerSymbol 8
set_interface_property PATERN_ESTIMATION_I burstOnBurstBoundariesOnly false
set_interface_property PATERN_ESTIMATION_I burstcountUnits WORDS
set_interface_property PATERN_ESTIMATION_I explicitAddressSpan 0
set_interface_property PATERN_ESTIMATION_I holdTime 0
set_interface_property PATERN_ESTIMATION_I linewrapBursts false
set_interface_property PATERN_ESTIMATION_I maximumPendingReadTransactions 0
set_interface_property PATERN_ESTIMATION_I maximumPendingWriteTransactions 0
set_interface_property PATERN_ESTIMATION_I readLatency 0
set_interface_property PATERN_ESTIMATION_I readWaitTime 1
set_interface_property PATERN_ESTIMATION_I setupTime 0
set_interface_property PATERN_ESTIMATION_I timingUnits Cycles
set_interface_property PATERN_ESTIMATION_I writeWaitTime 0
set_interface_property PATERN_ESTIMATION_I ENABLED true
set_interface_property PATERN_ESTIMATION_I EXPORT_OF ""
set_interface_property PATERN_ESTIMATION_I PORT_NAME_MAP ""
set_interface_property PATERN_ESTIMATION_I CMSIS_SVD_VARIABLES ""
set_interface_property PATERN_ESTIMATION_I SVD_ADDRESS_GROUP ""

add_interface_port PATERN_ESTIMATION_I PATERN_ESTIMATION_I writedata Input 32
add_interface_port PATERN_ESTIMATION_I avalon_slave_1_write write Input 1
set_interface_assignment PATERN_ESTIMATION_I embeddedsw.configuration.isFlash 0
set_interface_assignment PATERN_ESTIMATION_I embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment PATERN_ESTIMATION_I embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment PATERN_ESTIMATION_I embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ERROR_I_1_1
# 
add_interface ERROR_I_1_1 avalon end
set_interface_property ERROR_I_1_1 addressUnits WORDS
set_interface_property ERROR_I_1_1 associatedClock clock_sink
set_interface_property ERROR_I_1_1 associatedReset reset_sink
set_interface_property ERROR_I_1_1 bitsPerSymbol 8
set_interface_property ERROR_I_1_1 burstOnBurstBoundariesOnly false
set_interface_property ERROR_I_1_1 burstcountUnits WORDS
set_interface_property ERROR_I_1_1 explicitAddressSpan 0
set_interface_property ERROR_I_1_1 holdTime 0
set_interface_property ERROR_I_1_1 linewrapBursts false
set_interface_property ERROR_I_1_1 maximumPendingReadTransactions 0
set_interface_property ERROR_I_1_1 maximumPendingWriteTransactions 0
set_interface_property ERROR_I_1_1 readLatency 0
set_interface_property ERROR_I_1_1 readWaitTime 1
set_interface_property ERROR_I_1_1 setupTime 0
set_interface_property ERROR_I_1_1 timingUnits Cycles
set_interface_property ERROR_I_1_1 writeWaitTime 0
set_interface_property ERROR_I_1_1 ENABLED true
set_interface_property ERROR_I_1_1 EXPORT_OF ""
set_interface_property ERROR_I_1_1 PORT_NAME_MAP ""
set_interface_property ERROR_I_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property ERROR_I_1_1 SVD_ADDRESS_GROUP ""

add_interface_port ERROR_I_1_1 ERROR_I writedata Input 32
set_interface_assignment ERROR_I_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment ERROR_I_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ERROR_I_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ERROR_I_1_1 embeddedsw.configuration.isPrintableDevice 0

